name: "Terraform Destroy"

on:
  workflow_dispatch: # Manual trigger for the workflow

permissions:
  contents: read

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Plan the Destroy
      - name: Terraform Plan Destroy
        id: plan
        run: terraform plan -destroy -out=tfplan -no-color

      # Step 6: Pause for Manual Approval
      - name: Manual Approval
        run: |
          echo "Please review the Terraform destroy plan and approve to proceed."
          echo "To continue, click 'Re-run jobs' and approve the workflow."
        continue-on-error: true

      # Step 7: Apply the Destroy
      - name: Terraform Apply Destroy
        if: ${{ success() }}
        run: terraform apply -input=false tfplan